version: "3"
services:
  rides:
    container_name: rides
    restart: always
    build: ./Rides
    image: rides:latest
    ports:
      - 8000:5050
    links:
      - users
    depends_on:
      - rides_db
  users:
    container_name: users
    restart: always
    build: ./Users
    image: users:latest
    ports:
      - 8080:5000
    depends_on:
      - user_db
  user_db:
    container_name: users_db
    image: mongo

  rides_db:
    container_name: rides_db
    image: mongo
